# Generated by Django 3.2 on 2021-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_fen', models.TextField()),
                ('moves', models.TextField()),
                ('who_to_play', models.CharField(choices=[('W', 'White'), ('B', 'Black')], max_length=1)),
                ('piece_count', models.IntegerField()),
                ('piece_count_without_pawns', models.IntegerField()),
                ('white_pieces', models.JSONField()),
                ('black_pieces', models.JSONField()),
                ('rating', models.IntegerField()),
                ('rating_deviation', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('themes', models.TextField()),
                ('lichess_url', models.URLField()),
            ],
        ),
    ]
