# Generated by Django 3.2 on 2021-04-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='moves',
            field=models.JSONField(),
        ),
    ]
