# Generated by Django 3.2 on 2021-04-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_alter_puzzle_moves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='who_to_play',
            new_name='turn',
        ),
    ]
