# Generated by Django 3.2 on 2021-04-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_rename_who_to_play_puzzle_turn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ['piece_count', 'piece_count_without_pawns']},
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['piece_count'], name='puzzles_puz_piece_c_631a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='puzzle',
            index=models.Index(fields=['piece_count_without_pawns'], name='puzzles_puz_piece_c_0381b4_idx'),
        ),
    ]
