# Generated by Django 3.2 on 2021-04-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_auto_20210413_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='puzzles.puzzle')),
            ],
        ),
    ]
